baseURL = "https://margatroid.xyz"
languageCode = "zh-cn"
title = "Lunatic World"
metaDataFormat = "yaml"

theme = "canoe"

# use typora to editor new posts
newContentEditor = "typora"

# last mod time support
enableGitInfo = true

# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true

# DO　NOT MODIFY THIS CONFIG/不要修改这个配置
publishDir = "docs"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Margatroid"
  description = "帝乡不可期"
  copyright = "Copyright@Margatroid"
  # date format convert: http://fuckinggodateformat.com/
  dateFormat = "2006年01月_2日"
  # 用户头像地址, user avatar's url
  logo = "https://i.loli.net/2018/02/14/5a83925457828.png"

  # 首页横幅的背景链接, home banner's background url.
  splash_bg = "/img/bg.jpg"

  # 是否使用一言, if using hitokoto(dynamic moto phase in the home banner)
  hitokoto = false

  
# comment settings, support 'valine' and 'disqus'.
# more about 'valine', ref: http://valine.js.org/
[params.comment]
  type = "valine"

[params.comment.valine]
  id = "NAu3PVNY7rahbVOFB9rdX1Pc-gzGzoHsz"
  key = "HYsNt6ggO6z3PrfTH9QSvBg5"
  placeholder = "写点什么吧..."
  avatar = "retro"

[params.comment.disqus]
  shortname = 'keyin'


# Main menu
[[menu.main]]
    name = "Home"
    # associated with displaying order.
    weight = 1 
    url = "/"

[[menu.main]]
    name = "Archive"
    weight = 2
    url = "/archive/"
    
[[menu.main]]
    name = "About"
    weight = 6
    url = "/about/"



# 文章归类 Taxonomy
[[menu.taxonomy]]
  name = "Tag"
  identifier="tags"

[[menu.taxonomy]]
  name = "Category"
  identifier="categories"

#  友情链接 Your Friend's blog links
[[menu.friend]]
  name = "kZime"
  url = "http://kZime.xyz"

[[menu.friend]]
  name = "JustWB"
  url = "http://justwb.pro"

[[menu.friend]]
  name = "Ostmbh | mk学长"
  url = "http://blog.csdn.net/scaprt"

[[menu.friend]]
  name = "Kririae"
  url = "https://yuyuko.cc"

[[menu.friend]]
  name = "Von-Hyou | qwq教主"
  url = "http://von-hyou.pub"

[[menu.friend]]
  name = "KS"
  url = "http://ksmeow.moe"

[[menu.friend]]
  name = "Dedsecr"
  url = "https://dedsecr.github.io/"

[[menu.friend]]
  name = "封癫qwq"
  url = "http://www.cnblogs.com/cellular-automaton/"
  
[[menu.friend]]
  name = "_rqy dalao"
  url = "http://www.cnblogs.com/y-clever"
    
[[menu.friend]]
  name = "Shingen"
  url = "http://www.cnblogs.com/shingen/"
    
[[menu.friend]]
  name = "Hash_Table"
  url = "http://blog.csdn.net/Flere825"
    
[[menu.friend]]
  name = "applese"
  url = "http://blog.csdn.net/effervescence"
    
[[menu.friend]]
  name = "LittleRewriter"
  url = "http://blog.csdn.net/lirewriter"
    
[[menu.friend]]
  name = "Turkey"
  url = "http://www.cnblogs.com/hyghb/"

[[menu.friend]]
  name = "maoxiangui"
  url = "http://www.maoxiangui.com"
# 社交账号 Social Network
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  url = "https://github.com/enter-tainer"

# [[menu.social]]
#   pre = "<svg class='svg-icons svg-icons-twitter'><use xlink:href='#svg-icons-twitter'></use></svg>"
#   name = "Twitter"
#   url = "https://twitter.com/kevinsfork"

# [[menu.social]]
#   pre = "<svg class='svg-icons svg-icons-sina-weibo'><use xlink:href='#svg-icons-sina-weibo'></use></svg>"
#   name = "Weibo"
#   url = "http://weibo.com/kevinclasky"


[blackfriday]
  extensions = ["laxHtmlBlocks","noEmptyLineBeforeBlock","hardLineBreak"]
